### PR TITLE
[BUG] give error on CMS overflow

### LINKED ISSUE #418: CMS 32-bit overflow
If a CMS count reaches the max size of a 32-bit int, it will roll over to zero. This violates the never-underestimate-principle of CMS. The value should simply stop incrementing once it reaches the max value of a 32-bit int.

### PR DESCRIPTION
**Pull request by ashtul**
fixes #418 
Return an error message `CMS: INCRBY overflow` if overflow occurs on CMS.INCRBY.
CMS.QUERY will return `UINT32_MAX` or `4294967295`

### CODE REVIEW

File: src/cms.c [hunk 1]
```diff
@@ -52,14 +52,20 @@ size_t CMS_IncrBy(CMSketch *cms, const char *item, size_t itemlen, size_t value)
...
+        cms->array[loc] += value;
+        if (cms->array[loc] < value) {
+            cms->array[loc] = UINT32_MAX;
+            overflow = 1;
+        }
+        minCount = min(minCount, cms->array[loc]);
     }
     cms->counter += value;
-    return minCount;
+    return !overflow ? minCount : UINT32_MAX;
```
Comment (gkorland) [inline src/cms.c:68]:
```suggestion
    return overflow ? UINT32_MAX : minCount;
```

File: src/rm_cms.c [hunk 2]
```diff
@@ -133,7 +133,11 @@ int CMSketch_IncrBy(RedisModuleCtx *ctx, RedisModuleString **argv, int argc) {
     RedisModule_ReplyWithArray(ctx, pairCount);
     for (int i = 0; i < pairCount; ++i) {
         size_t count = CMS_IncrBy(cms, pairArray[i].key, pairArray[i].keylen, pairArray[i].value);
-        RedisModule_ReplyWithLongLong(ctx, (long long)count);
+        if (count != UINT32_MAX) {
+            RedisModule_ReplyWithLongLong(ctx, (long long)count);
+        } else {
+            RedisModule_ReplyWithError(ctx, "CMS: INCRBY overflow");
+        }
```
Comment (gkorland) [inline src/rm_cms.c:140]:
```suggestion
        if (count == UINT32_MAX) {
            RedisModule_ReplyWithError(ctx, "CMS: INCRBY overflow");
        } else {
            RedisModule_ReplyWithLongLong(ctx, (long long)count);
        }
```

File: tests/flow/test_cms.py [hunk 3]
```diff
@@ -177,6 +177,23 @@ def test_merge_extensive(self):
...
+        
+        self.cmd('FLUSHALL')
+        self.cmd('cms.initbydim', 'cms', '1000', '5')
+        self.assertEqual([large_val], self.cmd('cms.incrby', 'cms', 'a', large_val))
+        self.assertEqual([large_val], self.cmd('cms.query', 'cms', 'a'))
+        self.assertEqual([large_val * 2], self.cmd('cms.incrby', 'cms', 'a', large_val))
+        self.assertEqual([large_val * 2], self.cmd('cms.query', 'cms', 'a'))
+        
+        # overflow as result > UNIT32_MAX
+        res = self.cmd('cms.incrby', 'cms', 'a', large_val)
```
Comment (gkorland) [inline tests/flow/test_cms.py:191]: @ashtul please test with few tuples too.

```suggestion
        res = self.cmd('cms.incrby', 'cms', 'a', large_val, 'b', small_val, 'c', large_val)
```

File: src/cms.c (hunk 1 above)
Comment (gkorland) [reply src/cms.c:68]: Should you stop the loop after the first error?
If you return an error should you not leave the counter in its original form?

**Review by gkorland — CHANGES_REQUESTED** [review]

File: src/cms.c (hunk 1 above)
Comment (ashtul) [reply src/cms.c:68]: @gkorland I don't think we have to stop the loop. This means invalidating the sketch.
In future queries, since we take the minimum value, the sketch can still be used.

As for the order in condition, my preference is to have the common case before the exception. WDYT?

File: tests/flow/test_cms.py (hunk 3 above)
Comment (ashtul) [reply tests/flow/test_cms.py]: added additional elements

File: src/cms.c [hunk 4]
```diff
@@ -52,11 +47,16 @@ size_t CMS_IncrBy(CMSketch *cms, const char *item, size_t itemlen, size_t value)
     assert(item);
 
     size_t minCount = (size_t)-1;
+    int overflow = 0;
```
Comment (gkorland) [inline src/cms.c:50]:
```suggestion
```

**Review by gkorland — CHANGES_REQUESTED** [review]

**Review by filipecosta90 — APPROVED** [review]
